### PR TITLE
merged branches, fixed events css module

### PR DESCRIPTION
**Pull request by ujjujjuj**

### CODE REVIEW

**Comment by adnanhashmi09** [comment]
Your branch is probably not in sync with the dev branch. The event page looks really messy. And in mobile view, the content overflows.

**Comment by iShubhamRana** [comment]
Not updated , elements are enlarged. Please correct

**Comment by ujjujjuj** [comment]
i've fixed the css for the events page, it looks fine now

**Comment by adnanhashmi09** [comment]
Looks good to me

**Pull request merged**
