### PR TITLE
Home Page + Team Page + Responsive Footer

### PR DESCRIPTION
**Pull request by aryav-022**

### CODE REVIEW

**Comment by aryav-022** [comment]
1. Home Page Done (Except Reponsivmess)
2. Footer Done
3. Teams Page Prototyped
4. Reduced Spacing in Home Page
5. Implemented max-width = 1400px
6. Reduced section height from 500px to 400px
7. Added design component in Teams Page
8. Footer appended in each page (Easy Navigation Possible Now) 💯 

image

**Comment by adnanhashmi09** [comment]
1) The sections are not centered properly. They all get to the left. Use `margin: 0 auto` to center them. 
image

2) Footer is floating. Fix it to the bottom.
3) Don't give sections fixed height. Keep the height of the section dynamic (dependent on the content it holds).

**Comment by aryav-022** [comment]
You want me to keep footer visible on bottom of the screen?

**Comment by aryav-022** [comment]
New Home Page
image

**Comment by adnanhashmi09** [comment]
image

These are not aligned properly. Make images the same height.

**Comment by aryav-022** [comment]
> image
> 
> These are not aligned properly. Make images the same height.

Images are of same height, but some images have more white spacing than other... we may change the images later so i did not removed the white spacing of images

**Comment by aryav-022** [comment]
Home Page for Mobile upto 320px.
image
image

It is aligned but ss is croped from right for some reason.
image

**Comment by adnanhashmi09** [comment]
- [x] The alignment problem is fixed now but the images are stretchy. Add this property to the images where you have given them their height `object-fit: cover`.  
- [x] The content overflows in the `x axis` when in mobile view. 
- [x] The color of the font is not consistent with the design.

**Comment by adnanhashmi09** [comment]
Looks good. Maybe we can make the heading text bolder.

**Comment by aryav-022** [comment]
> Looks good. Maybe we can make the heading text bolder.

Which of these should be used?

1. `font-weight: 500`
image

2. `font-weight: 400`
image

3. `font-weight: normal`
image

I personally think that the current one (normal) is fine.

Here is another look:
image
image


here font-size is also increased along with `font-weight: 500`. This looks a bit oversized and a bit more bold (i think).

**Comment by adnanhashmi09** [comment]
okay cool.
Merged font changes into the development branch. Pull the latest updates

**Comment by aryav-022** [comment]
Pulled the updates. This changed the look a bit. Please see this once and tell if this is ok :)

**Pull request closed without merging**
